import os
import sys
import codecs
import numpy as np
import pickle
import Post
import FeatureExtractors as FE

glbl_bigraph = None
glbl_letterFrequency = None

def LoadUsers(filename):
  f = open(filename, 'r')
  users = f.read().split('\n')
  f.close()
  if users[len(users)-1] == "":
    del users[len(users)-1]
  return users

def LoadFeatures(featureFile, discretizationFile):
  global glbl_bigraph
  global glbl_letterFrequency
  f = open(featureFile, 'r')
  featureNames = f.read().split('\n')
  f.close()
  features = []
  if discretizationFile != "":
    f = open(discretizationFile, "rb")
    discretizations = pickle.load(f)
    f.close()
  else:
    discretizations = None
  for fName in featureNames:
    feat = None
    if fName == "numberofwords":
      feat = FE.NumberOfWords()
    if fName == "complexity":
      feat = FE.Complexity()
    if fName == "letterfraction":
      feat = FE.LetterFraction()
    if fName == "uppercasefraction":
      feat = FE.UppercaseFraction()
    if fName == "timeofposting":
      feat = FE.TimeOfPosting()
    if fName == "numberofcharacters":
      feat = FE.NumberOfCharacters()
    if fName == "whitespacefraction":
      feat = FE.WhitespaceFraction()
    if fName == "charactersperword":
      feat = FE.CharactersPerWord()
    if fName == "apostrophesperword":
      feat = FE.ApostrophesPerWord()
    if fName == "digitfraction":
      feat = FE.DigitFraction()
    if fName == "punctuationfraction":
      feat = FE.PunctuationFraction()
    if fName == "specialcharfraction":
      feat = FE.SpecialCharFraction()
    if fName == "emoticonsfraction":
      feat = FE.EmoticonsFraction()
    if fName[0:15] == "letterfrequency":
      redo = False
      if (glbl_letterFrequency == None):
        glbl_letterFrequency = FE.LetterFrequencies()
        redo = True
      if fName[16] == 'a':
        feat = FE.LetterFrequency_a(glbl_letterFrequency, redo)
      if fName[16] == 'b':
        feat = FE.LetterFrequency_b(glbl_letterFrequency, redo)
      if fName[16] == 'c':
        feat = FE.LetterFrequency_c(glbl_letterFrequency, redo)
      if fName[16] == 'd':
        feat = FE.LetterFrequency_d(glbl_letterFrequency, redo)
      if fName[16] == 'e':
        feat = FE.LetterFrequency_e(glbl_letterFrequency, redo)
      if fName[16] == 'f':
        feat = FE.LetterFrequency_f(glbl_letterFrequency, redo)
      if fName[16] == 'g':
        feat = FE.LetterFrequency_g(glbl_letterFrequency, redo)
      if fName[16] == 'h':
        feat = FE.LetterFrequency_h(glbl_letterFrequency, redo)
      if fName[16] == 'i':
        feat = FE.LetterFrequency_i(glbl_letterFrequency, redo)
      if fName[16] == 'j':
        feat = FE.LetterFrequency_j(glbl_letterFrequency, redo)
      if fName[16] == 'k':
        feat = FE.LetterFrequency_k(glbl_letterFrequency, redo)
      if fName[16] == 'l':
        feat = FE.LetterFrequency_l(glbl_letterFrequency, redo)
      if fName[16] == 'm':
        feat = FE.LetterFrequency_m(glbl_letterFrequency, redo)
      if fName[16] == 'n':
        feat = FE.LetterFrequency_n(glbl_letterFrequency, redo)
      if fName[16] == 'o':
        feat = FE.LetterFrequency_o(glbl_letterFrequency, redo)
      if fName[16] == 'p':
        feat = FE.LetterFrequency_p(glbl_letterFrequency, redo)
      if fName[16] == 'q':
        feat = FE.LetterFrequency_q(glbl_letterFrequency, redo)
      if fName[16] == 'r':
        feat = FE.LetterFrequency_r(glbl_letterFrequency, redo)
      if fName[16] == 's':
        feat = FE.LetterFrequency_s(glbl_letterFrequency, redo)
      if fName[16] == 't':
        feat = FE.LetterFrequency_t(glbl_letterFrequency, redo)
      if fName[16] == 'u':
        feat = FE.LetterFrequency_u(glbl_letterFrequency, redo)
      if fName[16] == 'v':
        feat = FE.LetterFrequency_v(glbl_letterFrequency, redo)
      if fName[16] == 'w':
        feat = FE.LetterFrequency_w(glbl_letterFrequency, redo)
      if fName[16] == 'x':
        feat = FE.LetterFrequency_x(glbl_letterFrequency, redo)
      if fName[16] == 'y':
        feat = FE.LetterFrequency_y(glbl_letterFrequency, redo)
      if fName[16] == 'z':
        feat = FE.LetterFrequency_z(glbl_letterFrequency, redo)
    if fName[0:7] == "bigraph":
      redo = False
      if (glbl_bigraph == None):
        glbl_bigraph = FE.Bigraph()
        redo = True
      if fName[8:10] == 'aa':
        feat = FE.Bigraph_aa(glbl_bigraph, redo)
      if fName[8:10] == 'ab':
        feat = FE.Bigraph_ab(glbl_bigraph, redo)
      if fName[8:10] == 'ac':
        feat = FE.Bigraph_ac(glbl_bigraph, redo)
      if fName[8:10] == 'ad':
        feat = FE.Bigraph_ad(glbl_bigraph, redo)
      if fName[8:10] == 'ae':
        feat = FE.Bigraph_ae(glbl_bigraph, redo)
      if fName[8:10] == 'af':
        feat = FE.Bigraph_af(glbl_bigraph, redo)
      if fName[8:10] == 'ag':
        feat = FE.Bigraph_ag(glbl_bigraph, redo)
      if fName[8:10] == 'ah':
        feat = FE.Bigraph_ah(glbl_bigraph, redo)
      if fName[8:10] == 'ai':
        feat = FE.Bigraph_ai(glbl_bigraph, redo)
      if fName[8:10] == 'aj':
        feat = FE.Bigraph_aj(glbl_bigraph, redo)
      if fName[8:10] == 'ak':
        feat = FE.Bigraph_ak(glbl_bigraph, redo)
      if fName[8:10] == 'al':
        feat = FE.Bigraph_al(glbl_bigraph, redo)
      if fName[8:10] == 'am':
        feat = FE.Bigraph_am(glbl_bigraph, redo)
      if fName[8:10] == 'an':
        feat = FE.Bigraph_an(glbl_bigraph, redo)
      if fName[8:10] == 'ao':
        feat = FE.Bigraph_ao(glbl_bigraph, redo)
      if fName[8:10] == 'ap':
        feat = FE.Bigraph_ap(glbl_bigraph, redo)
      if fName[8:10] == 'aq':
        feat = FE.Bigraph_aq(glbl_bigraph, redo)
      if fName[8:10] == 'ar':
        feat = FE.Bigraph_ar(glbl_bigraph, redo)
      if fName[8:10] == 'as':
        feat = FE.Bigraph_as(glbl_bigraph, redo)
      if fName[8:10] == 'at':
        feat = FE.Bigraph_at(glbl_bigraph, redo)
      if fName[8:10] == 'au':
        feat = FE.Bigraph_au(glbl_bigraph, redo)
      if fName[8:10] == 'av':
        feat = FE.Bigraph_av(glbl_bigraph, redo)
      if fName[8:10] == 'aw':
        feat = FE.Bigraph_aw(glbl_bigraph, redo)
      if fName[8:10] == 'ax':
        feat = FE.Bigraph_ax(glbl_bigraph, redo)
      if fName[8:10] == 'ay':
        feat = FE.Bigraph_ay(glbl_bigraph, redo)
      if fName[8:10] == 'az':
        feat = FE.Bigraph_az(glbl_bigraph, redo)
      if fName[8:10] == 'ba':
        feat = FE.Bigraph_ba(glbl_bigraph, redo)
      if fName[8:10] == 'bb':
        feat = FE.Bigraph_bb(glbl_bigraph, redo)
      if fName[8:10] == 'bc':
        feat = FE.Bigraph_bc(glbl_bigraph, redo)
      if fName[8:10] == 'bd':
        feat = FE.Bigraph_bd(glbl_bigraph, redo)
      if fName[8:10] == 'be':
        feat = FE.Bigraph_be(glbl_bigraph, redo)
      if fName[8:10] == 'bf':
        feat = FE.Bigraph_bf(glbl_bigraph, redo)
      if fName[8:10] == 'bg':
        feat = FE.Bigraph_bg(glbl_bigraph, redo)
      if fName[8:10] == 'bh':
        feat = FE.Bigraph_bh(glbl_bigraph, redo)
      if fName[8:10] == 'bi':
        feat = FE.Bigraph_bi(glbl_bigraph, redo)
      if fName[8:10] == 'bj':
        feat = FE.Bigraph_bj(glbl_bigraph, redo)
      if fName[8:10] == 'bk':
        feat = FE.Bigraph_bk(glbl_bigraph, redo)
      if fName[8:10] == 'bl':
        feat = FE.Bigraph_bl(glbl_bigraph, redo)
      if fName[8:10] == 'bm':
        feat = FE.Bigraph_bm(glbl_bigraph, redo)
      if fName[8:10] == 'bn':
        feat = FE.Bigraph_bn(glbl_bigraph, redo)
      if fName[8:10] == 'bo':
        feat = FE.Bigraph_bo(glbl_bigraph, redo)
      if fName[8:10] == 'bp':
        feat = FE.Bigraph_bp(glbl_bigraph, redo)
      if fName[8:10] == 'bq':
        feat = FE.Bigraph_bq(glbl_bigraph, redo)
      if fName[8:10] == 'br':
        feat = FE.Bigraph_br(glbl_bigraph, redo)
      if fName[8:10] == 'bs':
        feat = FE.Bigraph_bs(glbl_bigraph, redo)
      if fName[8:10] == 'bt':
        feat = FE.Bigraph_bt(glbl_bigraph, redo)
      if fName[8:10] == 'bu':
        feat = FE.Bigraph_bu(glbl_bigraph, redo)
      if fName[8:10] == 'bv':
        feat = FE.Bigraph_bv(glbl_bigraph, redo)
      if fName[8:10] == 'bw':
        feat = FE.Bigraph_bw(glbl_bigraph, redo)
      if fName[8:10] == 'bx':
        feat = FE.Bigraph_bx(glbl_bigraph, redo)
      if fName[8:10] == 'by':
        feat = FE.Bigraph_by(glbl_bigraph, redo)
      if fName[8:10] == 'bz':
        feat = FE.Bigraph_bz(glbl_bigraph, redo)
      if fName[8:10] == 'ca':
        feat = FE.Bigraph_ca(glbl_bigraph, redo)
      if fName[8:10] == 'cb':
        feat = FE.Bigraph_cb(glbl_bigraph, redo)
      if fName[8:10] == 'cc':
        feat = FE.Bigraph_cc(glbl_bigraph, redo)
      if fName[8:10] == 'cd':
        feat = FE.Bigraph_cd(glbl_bigraph, redo)
      if fName[8:10] == 'ce':
        feat = FE.Bigraph_ce(glbl_bigraph, redo)
      if fName[8:10] == 'cf':
        feat = FE.Bigraph_cf(glbl_bigraph, redo)
      if fName[8:10] == 'cg':
        feat = FE.Bigraph_cg(glbl_bigraph, redo)
      if fName[8:10] == 'ch':
        feat = FE.Bigraph_ch(glbl_bigraph, redo)
      if fName[8:10] == 'ci':
        feat = FE.Bigraph_ci(glbl_bigraph, redo)
      if fName[8:10] == 'cj':
        feat = FE.Bigraph_cj(glbl_bigraph, redo)
      if fName[8:10] == 'ck':
        feat = FE.Bigraph_ck(glbl_bigraph, redo)
      if fName[8:10] == 'cl':
        feat = FE.Bigraph_cl(glbl_bigraph, redo)
      if fName[8:10] == 'cm':
        feat = FE.Bigraph_cm(glbl_bigraph, redo)
      if fName[8:10] == 'cn':
        feat = FE.Bigraph_cn(glbl_bigraph, redo)
      if fName[8:10] == 'co':
        feat = FE.Bigraph_co(glbl_bigraph, redo)
      if fName[8:10] == 'cp':
        feat = FE.Bigraph_cp(glbl_bigraph, redo)
      if fName[8:10] == 'cq':
        feat = FE.Bigraph_cq(glbl_bigraph, redo)
      if fName[8:10] == 'cr':
        feat = FE.Bigraph_cr(glbl_bigraph, redo)
      if fName[8:10] == 'cs':
        feat = FE.Bigraph_cs(glbl_bigraph, redo)
      if fName[8:10] == 'ct':
        feat = FE.Bigraph_ct(glbl_bigraph, redo)
      if fName[8:10] == 'cu':
        feat = FE.Bigraph_cu(glbl_bigraph, redo)
      if fName[8:10] == 'cv':
        feat = FE.Bigraph_cv(glbl_bigraph, redo)
      if fName[8:10] == 'cw':
        feat = FE.Bigraph_cw(glbl_bigraph, redo)
      if fName[8:10] == 'cx':
        feat = FE.Bigraph_cx(glbl_bigraph, redo)
      if fName[8:10] == 'cy':
        feat = FE.Bigraph_cy(glbl_bigraph, redo)
      if fName[8:10] == 'cz':
        feat = FE.Bigraph_cz(glbl_bigraph, redo)
      if fName[8:10] == 'da':
        feat = FE.Bigraph_da(glbl_bigraph, redo)
      if fName[8:10] == 'db':
        feat = FE.Bigraph_db(glbl_bigraph, redo)
      if fName[8:10] == 'dc':
        feat = FE.Bigraph_dc(glbl_bigraph, redo)
      if fName[8:10] == 'dd':
        feat = FE.Bigraph_dd(glbl_bigraph, redo)
      if fName[8:10] == 'de':
        feat = FE.Bigraph_de(glbl_bigraph, redo)
      if fName[8:10] == 'df':
        feat = FE.Bigraph_df(glbl_bigraph, redo)
      if fName[8:10] == 'dg':
        feat = FE.Bigraph_dg(glbl_bigraph, redo)
      if fName[8:10] == 'dh':
        feat = FE.Bigraph_dh(glbl_bigraph, redo)
      if fName[8:10] == 'di':
        feat = FE.Bigraph_di(glbl_bigraph, redo)
      if fName[8:10] == 'dj':
        feat = FE.Bigraph_dj(glbl_bigraph, redo)
      if fName[8:10] == 'dk':
        feat = FE.Bigraph_dk(glbl_bigraph, redo)
      if fName[8:10] == 'dl':
        feat = FE.Bigraph_dl(glbl_bigraph, redo)
      if fName[8:10] == 'dm':
        feat = FE.Bigraph_dm(glbl_bigraph, redo)
      if fName[8:10] == 'dn':
        feat = FE.Bigraph_dn(glbl_bigraph, redo)
      if fName[8:10] == 'do':
        feat = FE.Bigraph_do(glbl_bigraph, redo)
      if fName[8:10] == 'dp':
        feat = FE.Bigraph_dp(glbl_bigraph, redo)
      if fName[8:10] == 'dq':
        feat = FE.Bigraph_dq(glbl_bigraph, redo)
      if fName[8:10] == 'dr':
        feat = FE.Bigraph_dr(glbl_bigraph, redo)
      if fName[8:10] == 'ds':
        feat = FE.Bigraph_ds(glbl_bigraph, redo)
      if fName[8:10] == 'dt':
        feat = FE.Bigraph_dt(glbl_bigraph, redo)
      if fName[8:10] == 'du':
        feat = FE.Bigraph_du(glbl_bigraph, redo)
      if fName[8:10] == 'dv':
        feat = FE.Bigraph_dv(glbl_bigraph, redo)
      if fName[8:10] == 'dw':
        feat = FE.Bigraph_dw(glbl_bigraph, redo)
      if fName[8:10] == 'dx':
        feat = FE.Bigraph_dx(glbl_bigraph, redo)
      if fName[8:10] == 'dy':
        feat = FE.Bigraph_dy(glbl_bigraph, redo)
      if fName[8:10] == 'dz':
        feat = FE.Bigraph_dz(glbl_bigraph, redo)
      if fName[8:10] == 'ea':
        feat = FE.Bigraph_ea(glbl_bigraph, redo)
      if fName[8:10] == 'eb':
        feat = FE.Bigraph_eb(glbl_bigraph, redo)
      if fName[8:10] == 'ec':
        feat = FE.Bigraph_ec(glbl_bigraph, redo)
      if fName[8:10] == 'ed':
        feat = FE.Bigraph_ed(glbl_bigraph, redo)
      if fName[8:10] == 'ee':
        feat = FE.Bigraph_ee(glbl_bigraph, redo)
      if fName[8:10] == 'ef':
        feat = FE.Bigraph_ef(glbl_bigraph, redo)
      if fName[8:10] == 'eg':
        feat = FE.Bigraph_eg(glbl_bigraph, redo)
      if fName[8:10] == 'eh':
        feat = FE.Bigraph_eh(glbl_bigraph, redo)
      if fName[8:10] == 'ei':
        feat = FE.Bigraph_ei(glbl_bigraph, redo)
      if fName[8:10] == 'ej':
        feat = FE.Bigraph_ej(glbl_bigraph, redo)
      if fName[8:10] == 'ek':
        feat = FE.Bigraph_ek(glbl_bigraph, redo)
      if fName[8:10] == 'el':
        feat = FE.Bigraph_el(glbl_bigraph, redo)
      if fName[8:10] == 'em':
        feat = FE.Bigraph_em(glbl_bigraph, redo)
      if fName[8:10] == 'en':
        feat = FE.Bigraph_en(glbl_bigraph, redo)
      if fName[8:10] == 'eo':
        feat = FE.Bigraph_eo(glbl_bigraph, redo)
      if fName[8:10] == 'ep':
        feat = FE.Bigraph_ep(glbl_bigraph, redo)
      if fName[8:10] == 'eq':
        feat = FE.Bigraph_eq(glbl_bigraph, redo)
      if fName[8:10] == 'er':
        feat = FE.Bigraph_er(glbl_bigraph, redo)
      if fName[8:10] == 'es':
        feat = FE.Bigraph_es(glbl_bigraph, redo)
      if fName[8:10] == 'et':
        feat = FE.Bigraph_et(glbl_bigraph, redo)
      if fName[8:10] == 'eu':
        feat = FE.Bigraph_eu(glbl_bigraph, redo)
      if fName[8:10] == 'ev':
        feat = FE.Bigraph_ev(glbl_bigraph, redo)
      if fName[8:10] == 'ew':
        feat = FE.Bigraph_ew(glbl_bigraph, redo)
      if fName[8:10] == 'ex':
        feat = FE.Bigraph_ex(glbl_bigraph, redo)
      if fName[8:10] == 'ey':
        feat = FE.Bigraph_ey(glbl_bigraph, redo)
      if fName[8:10] == 'ez':
        feat = FE.Bigraph_ez(glbl_bigraph, redo)
      if fName[8:10] == 'fa':
        feat = FE.Bigraph_fa(glbl_bigraph, redo)
      if fName[8:10] == 'fb':
        feat = FE.Bigraph_fb(glbl_bigraph, redo)
      if fName[8:10] == 'fc':
        feat = FE.Bigraph_fc(glbl_bigraph, redo)
      if fName[8:10] == 'fd':
        feat = FE.Bigraph_fd(glbl_bigraph, redo)
      if fName[8:10] == 'fe':
        feat = FE.Bigraph_fe(glbl_bigraph, redo)
      if fName[8:10] == 'ff':
        feat = FE.Bigraph_ff(glbl_bigraph, redo)
      if fName[8:10] == 'fg':
        feat = FE.Bigraph_fg(glbl_bigraph, redo)
      if fName[8:10] == 'fh':
        feat = FE.Bigraph_fh(glbl_bigraph, redo)
      if fName[8:10] == 'fi':
        feat = FE.Bigraph_fi(glbl_bigraph, redo)
      if fName[8:10] == 'fj':
        feat = FE.Bigraph_fj(glbl_bigraph, redo)
      if fName[8:10] == 'fk':
        feat = FE.Bigraph_fk(glbl_bigraph, redo)
      if fName[8:10] == 'fl':
        feat = FE.Bigraph_fl(glbl_bigraph, redo)
      if fName[8:10] == 'fm':
        feat = FE.Bigraph_fm(glbl_bigraph, redo)
      if fName[8:10] == 'fn':
        feat = FE.Bigraph_fn(glbl_bigraph, redo)
      if fName[8:10] == 'fo':
        feat = FE.Bigraph_fo(glbl_bigraph, redo)
      if fName[8:10] == 'fp':
        feat = FE.Bigraph_fp(glbl_bigraph, redo)
      if fName[8:10] == 'fq':
        feat = FE.Bigraph_fq(glbl_bigraph, redo)
      if fName[8:10] == 'fr':
        feat = FE.Bigraph_fr(glbl_bigraph, redo)
      if fName[8:10] == 'fs':
        feat = FE.Bigraph_fs(glbl_bigraph, redo)
      if fName[8:10] == 'ft':
        feat = FE.Bigraph_ft(glbl_bigraph, redo)
      if fName[8:10] == 'fu':
        feat = FE.Bigraph_fu(glbl_bigraph, redo)
      if fName[8:10] == 'fv':
        feat = FE.Bigraph_fv(glbl_bigraph, redo)
      if fName[8:10] == 'fw':
        feat = FE.Bigraph_fw(glbl_bigraph, redo)
      if fName[8:10] == 'fx':
        feat = FE.Bigraph_fx(glbl_bigraph, redo)
      if fName[8:10] == 'fy':
        feat = FE.Bigraph_fy(glbl_bigraph, redo)
      if fName[8:10] == 'fz':
        feat = FE.Bigraph_fz(glbl_bigraph, redo)
      if fName[8:10] == 'ga':
        feat = FE.Bigraph_ga(glbl_bigraph, redo)
      if fName[8:10] == 'gb':
        feat = FE.Bigraph_gb(glbl_bigraph, redo)
      if fName[8:10] == 'gc':
        feat = FE.Bigraph_gc(glbl_bigraph, redo)
      if fName[8:10] == 'gd':
        feat = FE.Bigraph_gd(glbl_bigraph, redo)
      if fName[8:10] == 'ge':
        feat = FE.Bigraph_ge(glbl_bigraph, redo)
      if fName[8:10] == 'gf':
        feat = FE.Bigraph_gf(glbl_bigraph, redo)
      if fName[8:10] == 'gg':
        feat = FE.Bigraph_gg(glbl_bigraph, redo)
      if fName[8:10] == 'gh':
        feat = FE.Bigraph_gh(glbl_bigraph, redo)
      if fName[8:10] == 'gi':
        feat = FE.Bigraph_gi(glbl_bigraph, redo)
      if fName[8:10] == 'gj':
        feat = FE.Bigraph_gj(glbl_bigraph, redo)
      if fName[8:10] == 'gk':
        feat = FE.Bigraph_gk(glbl_bigraph, redo)
      if fName[8:10] == 'gl':
        feat = FE.Bigraph_gl(glbl_bigraph, redo)
      if fName[8:10] == 'gm':
        feat = FE.Bigraph_gm(glbl_bigraph, redo)
      if fName[8:10] == 'gn':
        feat = FE.Bigraph_gn(glbl_bigraph, redo)
      if fName[8:10] == 'go':
        feat = FE.Bigraph_go(glbl_bigraph, redo)
      if fName[8:10] == 'gp':
        feat = FE.Bigraph_gp(glbl_bigraph, redo)
      if fName[8:10] == 'gq':
        feat = FE.Bigraph_gq(glbl_bigraph, redo)
      if fName[8:10] == 'gr':
        feat = FE.Bigraph_gr(glbl_bigraph, redo)
      if fName[8:10] == 'gs':
        feat = FE.Bigraph_gs(glbl_bigraph, redo)
      if fName[8:10] == 'gt':
        feat = FE.Bigraph_gt(glbl_bigraph, redo)
      if fName[8:10] == 'gu':
        feat = FE.Bigraph_gu(glbl_bigraph, redo)
      if fName[8:10] == 'gv':
        feat = FE.Bigraph_gv(glbl_bigraph, redo)
      if fName[8:10] == 'gw':
        feat = FE.Bigraph_gw(glbl_bigraph, redo)
      if fName[8:10] == 'gx':
        feat = FE.Bigraph_gx(glbl_bigraph, redo)
      if fName[8:10] == 'gy':
        feat = FE.Bigraph_gy(glbl_bigraph, redo)
      if fName[8:10] == 'gz':
        feat = FE.Bigraph_gz(glbl_bigraph, redo)
      if fName[8:10] == 'ha':
        feat = FE.Bigraph_ha(glbl_bigraph, redo)
      if fName[8:10] == 'hb':
        feat = FE.Bigraph_hb(glbl_bigraph, redo)
      if fName[8:10] == 'hc':
        feat = FE.Bigraph_hc(glbl_bigraph, redo)
      if fName[8:10] == 'hd':
        feat = FE.Bigraph_hd(glbl_bigraph, redo)
      if fName[8:10] == 'he':
        feat = FE.Bigraph_he(glbl_bigraph, redo)
      if fName[8:10] == 'hf':
        feat = FE.Bigraph_hf(glbl_bigraph, redo)
      if fName[8:10] == 'hg':
        feat = FE.Bigraph_hg(glbl_bigraph, redo)
      if fName[8:10] == 'hh':
        feat = FE.Bigraph_hh(glbl_bigraph, redo)
      if fName[8:10] == 'hi':
        feat = FE.Bigraph_hi(glbl_bigraph, redo)
      if fName[8:10] == 'hj':
        feat = FE.Bigraph_hj(glbl_bigraph, redo)
      if fName[8:10] == 'hk':
        feat = FE.Bigraph_hk(glbl_bigraph, redo)
      if fName[8:10] == 'hl':
        feat = FE.Bigraph_hl(glbl_bigraph, redo)
      if fName[8:10] == 'hm':
        feat = FE.Bigraph_hm(glbl_bigraph, redo)
      if fName[8:10] == 'hn':
        feat = FE.Bigraph_hn(glbl_bigraph, redo)
      if fName[8:10] == 'ho':
        feat = FE.Bigraph_ho(glbl_bigraph, redo)
      if fName[8:10] == 'hp':
        feat = FE.Bigraph_hp(glbl_bigraph, redo)
      if fName[8:10] == 'hq':
        feat = FE.Bigraph_hq(glbl_bigraph, redo)
      if fName[8:10] == 'hr':
        feat = FE.Bigraph_hr(glbl_bigraph, redo)
      if fName[8:10] == 'hs':
        feat = FE.Bigraph_hs(glbl_bigraph, redo)
      if fName[8:10] == 'ht':
        feat = FE.Bigraph_ht(glbl_bigraph, redo)
      if fName[8:10] == 'hu':
        feat = FE.Bigraph_hu(glbl_bigraph, redo)
      if fName[8:10] == 'hv':
        feat = FE.Bigraph_hv(glbl_bigraph, redo)
      if fName[8:10] == 'hw':
        feat = FE.Bigraph_hw(glbl_bigraph, redo)
      if fName[8:10] == 'hx':
        feat = FE.Bigraph_hx(glbl_bigraph, redo)
      if fName[8:10] == 'hy':
        feat = FE.Bigraph_hy(glbl_bigraph, redo)
      if fName[8:10] == 'hz':
        feat = FE.Bigraph_hz(glbl_bigraph, redo)
      if fName[8:10] == 'ia':
        feat = FE.Bigraph_ia(glbl_bigraph, redo)
      if fName[8:10] == 'ib':
        feat = FE.Bigraph_ib(glbl_bigraph, redo)
      if fName[8:10] == 'ic':
        feat = FE.Bigraph_ic(glbl_bigraph, redo)
      if fName[8:10] == 'id':
        feat = FE.Bigraph_id(glbl_bigraph, redo)
      if fName[8:10] == 'ie':
        feat = FE.Bigraph_ie(glbl_bigraph, redo)
      if fName[8:10] == 'if':
        feat = FE.Bigraph_if(glbl_bigraph, redo)
      if fName[8:10] == 'ig':
        feat = FE.Bigraph_ig(glbl_bigraph, redo)
      if fName[8:10] == 'ih':
        feat = FE.Bigraph_ih(glbl_bigraph, redo)
      if fName[8:10] == 'ii':
        feat = FE.Bigraph_ii(glbl_bigraph, redo)
      if fName[8:10] == 'ij':
        feat = FE.Bigraph_ij(glbl_bigraph, redo)
      if fName[8:10] == 'ik':
        feat = FE.Bigraph_ik(glbl_bigraph, redo)
      if fName[8:10] == 'il':
        feat = FE.Bigraph_il(glbl_bigraph, redo)
      if fName[8:10] == 'im':
        feat = FE.Bigraph_im(glbl_bigraph, redo)
      if fName[8:10] == 'in':
        feat = FE.Bigraph_in(glbl_bigraph, redo)
      if fName[8:10] == 'io':
        feat = FE.Bigraph_io(glbl_bigraph, redo)
      if fName[8:10] == 'ip':
        feat = FE.Bigraph_ip(glbl_bigraph, redo)
      if fName[8:10] == 'iq':
        feat = FE.Bigraph_iq(glbl_bigraph, redo)
      if fName[8:10] == 'ir':
        feat = FE.Bigraph_ir(glbl_bigraph, redo)
      if fName[8:10] == 'is':
        feat = FE.Bigraph_is(glbl_bigraph, redo)
      if fName[8:10] == 'it':
        feat = FE.Bigraph_it(glbl_bigraph, redo)
      if fName[8:10] == 'iu':
        feat = FE.Bigraph_iu(glbl_bigraph, redo)
      if fName[8:10] == 'iv':
        feat = FE.Bigraph_iv(glbl_bigraph, redo)
      if fName[8:10] == 'iw':
        feat = FE.Bigraph_iw(glbl_bigraph, redo)
      if fName[8:10] == 'ix':
        feat = FE.Bigraph_ix(glbl_bigraph, redo)
      if fName[8:10] == 'iy':
        feat = FE.Bigraph_iy(glbl_bigraph, redo)
      if fName[8:10] == 'iz':
        feat = FE.Bigraph_iz(glbl_bigraph, redo)
      if fName[8:10] == 'ja':
        feat = FE.Bigraph_ja(glbl_bigraph, redo)
      if fName[8:10] == 'jb':
        feat = FE.Bigraph_jb(glbl_bigraph, redo)
      if fName[8:10] == 'jc':
        feat = FE.Bigraph_jc(glbl_bigraph, redo)
      if fName[8:10] == 'jd':
        feat = FE.Bigraph_jd(glbl_bigraph, redo)
      if fName[8:10] == 'je':
        feat = FE.Bigraph_je(glbl_bigraph, redo)
      if fName[8:10] == 'jf':
        feat = FE.Bigraph_jf(glbl_bigraph, redo)
      if fName[8:10] == 'jg':
        feat = FE.Bigraph_jg(glbl_bigraph, redo)
      if fName[8:10] == 'jh':
        feat = FE.Bigraph_jh(glbl_bigraph, redo)
      if fName[8:10] == 'ji':
        feat = FE.Bigraph_ji(glbl_bigraph, redo)
      if fName[8:10] == 'jj':
        feat = FE.Bigraph_jj(glbl_bigraph, redo)
      if fName[8:10] == 'jk':
        feat = FE.Bigraph_jk(glbl_bigraph, redo)
      if fName[8:10] == 'jl':
        feat = FE.Bigraph_jl(glbl_bigraph, redo)
      if fName[8:10] == 'jm':
        feat = FE.Bigraph_jm(glbl_bigraph, redo)
      if fName[8:10] == 'jn':
        feat = FE.Bigraph_jn(glbl_bigraph, redo)
      if fName[8:10] == 'jo':
        feat = FE.Bigraph_jo(glbl_bigraph, redo)
      if fName[8:10] == 'jp':
        feat = FE.Bigraph_jp(glbl_bigraph, redo)
      if fName[8:10] == 'jq':
        feat = FE.Bigraph_jq(glbl_bigraph, redo)
      if fName[8:10] == 'jr':
        feat = FE.Bigraph_jr(glbl_bigraph, redo)
      if fName[8:10] == 'js':
        feat = FE.Bigraph_js(glbl_bigraph, redo)
      if fName[8:10] == 'jt':
        feat = FE.Bigraph_jt(glbl_bigraph, redo)
      if fName[8:10] == 'ju':
        feat = FE.Bigraph_ju(glbl_bigraph, redo)
      if fName[8:10] == 'jv':
        feat = FE.Bigraph_jv(glbl_bigraph, redo)
      if fName[8:10] == 'jw':
        feat = FE.Bigraph_jw(glbl_bigraph, redo)
      if fName[8:10] == 'jx':
        feat = FE.Bigraph_jx(glbl_bigraph, redo)
      if fName[8:10] == 'jy':
        feat = FE.Bigraph_jy(glbl_bigraph, redo)
      if fName[8:10] == 'jz':
        feat = FE.Bigraph_jz(glbl_bigraph, redo)
      if fName[8:10] == 'ka':
        feat = FE.Bigraph_ka(glbl_bigraph, redo)
      if fName[8:10] == 'kb':
        feat = FE.Bigraph_kb(glbl_bigraph, redo)
      if fName[8:10] == 'kc':
        feat = FE.Bigraph_kc(glbl_bigraph, redo)
      if fName[8:10] == 'kd':
        feat = FE.Bigraph_kd(glbl_bigraph, redo)
      if fName[8:10] == 'ke':
        feat = FE.Bigraph_ke(glbl_bigraph, redo)
      if fName[8:10] == 'kf':
        feat = FE.Bigraph_kf(glbl_bigraph, redo)
      if fName[8:10] == 'kg':
        feat = FE.Bigraph_kg(glbl_bigraph, redo)
      if fName[8:10] == 'kh':
        feat = FE.Bigraph_kh(glbl_bigraph, redo)
      if fName[8:10] == 'ki':
        feat = FE.Bigraph_ki(glbl_bigraph, redo)
      if fName[8:10] == 'kj':
        feat = FE.Bigraph_kj(glbl_bigraph, redo)
      if fName[8:10] == 'kk':
        feat = FE.Bigraph_kk(glbl_bigraph, redo)
      if fName[8:10] == 'kl':
        feat = FE.Bigraph_kl(glbl_bigraph, redo)
      if fName[8:10] == 'km':
        feat = FE.Bigraph_km(glbl_bigraph, redo)
      if fName[8:10] == 'kn':
        feat = FE.Bigraph_kn(glbl_bigraph, redo)
      if fName[8:10] == 'ko':
        feat = FE.Bigraph_ko(glbl_bigraph, redo)
      if fName[8:10] == 'kp':
        feat = FE.Bigraph_kp(glbl_bigraph, redo)
      if fName[8:10] == 'kq':
        feat = FE.Bigraph_kq(glbl_bigraph, redo)
      if fName[8:10] == 'kr':
        feat = FE.Bigraph_kr(glbl_bigraph, redo)
      if fName[8:10] == 'ks':
        feat = FE.Bigraph_ks(glbl_bigraph, redo)
      if fName[8:10] == 'kt':
        feat = FE.Bigraph_kt(glbl_bigraph, redo)
      if fName[8:10] == 'ku':
        feat = FE.Bigraph_ku(glbl_bigraph, redo)
      if fName[8:10] == 'kv':
        feat = FE.Bigraph_kv(glbl_bigraph, redo)
      if fName[8:10] == 'kw':
        feat = FE.Bigraph_kw(glbl_bigraph, redo)
      if fName[8:10] == 'kx':
        feat = FE.Bigraph_kx(glbl_bigraph, redo)
      if fName[8:10] == 'ky':
        feat = FE.Bigraph_ky(glbl_bigraph, redo)
      if fName[8:10] == 'kz':
        feat = FE.Bigraph_kz(glbl_bigraph, redo)
      if fName[8:10] == 'la':
        feat = FE.Bigraph_la(glbl_bigraph, redo)
      if fName[8:10] == 'lb':
        feat = FE.Bigraph_lb(glbl_bigraph, redo)
      if fName[8:10] == 'lc':
        feat = FE.Bigraph_lc(glbl_bigraph, redo)
      if fName[8:10] == 'ld':
        feat = FE.Bigraph_ld(glbl_bigraph, redo)
      if fName[8:10] == 'le':
        feat = FE.Bigraph_le(glbl_bigraph, redo)
      if fName[8:10] == 'lf':
        feat = FE.Bigraph_lf(glbl_bigraph, redo)
      if fName[8:10] == 'lg':
        feat = FE.Bigraph_lg(glbl_bigraph, redo)
      if fName[8:10] == 'lh':
        feat = FE.Bigraph_lh(glbl_bigraph, redo)
      if fName[8:10] == 'li':
        feat = FE.Bigraph_li(glbl_bigraph, redo)
      if fName[8:10] == 'lj':
        feat = FE.Bigraph_lj(glbl_bigraph, redo)
      if fName[8:10] == 'lk':
        feat = FE.Bigraph_lk(glbl_bigraph, redo)
      if fName[8:10] == 'll':
        feat = FE.Bigraph_ll(glbl_bigraph, redo)
      if fName[8:10] == 'lm':
        feat = FE.Bigraph_lm(glbl_bigraph, redo)
      if fName[8:10] == 'ln':
        feat = FE.Bigraph_ln(glbl_bigraph, redo)
      if fName[8:10] == 'lo':
        feat = FE.Bigraph_lo(glbl_bigraph, redo)
      if fName[8:10] == 'lp':
        feat = FE.Bigraph_lp(glbl_bigraph, redo)
      if fName[8:10] == 'lq':
        feat = FE.Bigraph_lq(glbl_bigraph, redo)
      if fName[8:10] == 'lr':
        feat = FE.Bigraph_lr(glbl_bigraph, redo)
      if fName[8:10] == 'ls':
        feat = FE.Bigraph_ls(glbl_bigraph, redo)
      if fName[8:10] == 'lt':
        feat = FE.Bigraph_lt(glbl_bigraph, redo)
      if fName[8:10] == 'lu':
        feat = FE.Bigraph_lu(glbl_bigraph, redo)
      if fName[8:10] == 'lv':
        feat = FE.Bigraph_lv(glbl_bigraph, redo)
      if fName[8:10] == 'lw':
        feat = FE.Bigraph_lw(glbl_bigraph, redo)
      if fName[8:10] == 'lx':
        feat = FE.Bigraph_lx(glbl_bigraph, redo)
      if fName[8:10] == 'ly':
        feat = FE.Bigraph_ly(glbl_bigraph, redo)
      if fName[8:10] == 'lz':
        feat = FE.Bigraph_lz(glbl_bigraph, redo)
      if fName[8:10] == 'ma':
        feat = FE.Bigraph_ma(glbl_bigraph, redo)
      if fName[8:10] == 'mb':
        feat = FE.Bigraph_mb(glbl_bigraph, redo)
      if fName[8:10] == 'mc':
        feat = FE.Bigraph_mc(glbl_bigraph, redo)
      if fName[8:10] == 'md':
        feat = FE.Bigraph_md(glbl_bigraph, redo)
      if fName[8:10] == 'me':
        feat = FE.Bigraph_me(glbl_bigraph, redo)
      if fName[8:10] == 'mf':
        feat = FE.Bigraph_mf(glbl_bigraph, redo)
      if fName[8:10] == 'mg':
        feat = FE.Bigraph_mg(glbl_bigraph, redo)
      if fName[8:10] == 'mh':
        feat = FE.Bigraph_mh(glbl_bigraph, redo)
      if fName[8:10] == 'mi':
        feat = FE.Bigraph_mi(glbl_bigraph, redo)
      if fName[8:10] == 'mj':
        feat = FE.Bigraph_mj(glbl_bigraph, redo)
      if fName[8:10] == 'mk':
        feat = FE.Bigraph_mk(glbl_bigraph, redo)
      if fName[8:10] == 'ml':
        feat = FE.Bigraph_ml(glbl_bigraph, redo)
      if fName[8:10] == 'mm':
        feat = FE.Bigraph_mm(glbl_bigraph, redo)
      if fName[8:10] == 'mn':
        feat = FE.Bigraph_mn(glbl_bigraph, redo)
      if fName[8:10] == 'mo':
        feat = FE.Bigraph_mo(glbl_bigraph, redo)
      if fName[8:10] == 'mp':
        feat = FE.Bigraph_mp(glbl_bigraph, redo)
      if fName[8:10] == 'mq':
        feat = FE.Bigraph_mq(glbl_bigraph, redo)
      if fName[8:10] == 'mr':
        feat = FE.Bigraph_mr(glbl_bigraph, redo)
      if fName[8:10] == 'ms':
        feat = FE.Bigraph_ms(glbl_bigraph, redo)
      if fName[8:10] == 'mt':
        feat = FE.Bigraph_mt(glbl_bigraph, redo)
      if fName[8:10] == 'mu':
        feat = FE.Bigraph_mu(glbl_bigraph, redo)
      if fName[8:10] == 'mv':
        feat = FE.Bigraph_mv(glbl_bigraph, redo)
      if fName[8:10] == 'mw':
        feat = FE.Bigraph_mw(glbl_bigraph, redo)
      if fName[8:10] == 'mx':
        feat = FE.Bigraph_mx(glbl_bigraph, redo)
      if fName[8:10] == 'my':
        feat = FE.Bigraph_my(glbl_bigraph, redo)
      if fName[8:10] == 'mz':
        feat = FE.Bigraph_mz(glbl_bigraph, redo)
      if fName[8:10] == 'na':
        feat = FE.Bigraph_na(glbl_bigraph, redo)
      if fName[8:10] == 'nb':
        feat = FE.Bigraph_nb(glbl_bigraph, redo)
      if fName[8:10] == 'nc':
        feat = FE.Bigraph_nc(glbl_bigraph, redo)
      if fName[8:10] == 'nd':
        feat = FE.Bigraph_nd(glbl_bigraph, redo)
      if fName[8:10] == 'ne':
        feat = FE.Bigraph_ne(glbl_bigraph, redo)
      if fName[8:10] == 'nf':
        feat = FE.Bigraph_nf(glbl_bigraph, redo)
      if fName[8:10] == 'ng':
        feat = FE.Bigraph_ng(glbl_bigraph, redo)
      if fName[8:10] == 'nh':
        feat = FE.Bigraph_nh(glbl_bigraph, redo)
      if fName[8:10] == 'ni':
        feat = FE.Bigraph_ni(glbl_bigraph, redo)
      if fName[8:10] == 'nj':
        feat = FE.Bigraph_nj(glbl_bigraph, redo)
      if fName[8:10] == 'nk':
        feat = FE.Bigraph_nk(glbl_bigraph, redo)
      if fName[8:10] == 'nl':
        feat = FE.Bigraph_nl(glbl_bigraph, redo)
      if fName[8:10] == 'nm':
        feat = FE.Bigraph_nm(glbl_bigraph, redo)
      if fName[8:10] == 'nn':
        feat = FE.Bigraph_nn(glbl_bigraph, redo)
      if fName[8:10] == 'no':
        feat = FE.Bigraph_no(glbl_bigraph, redo)
      if fName[8:10] == 'np':
        feat = FE.Bigraph_np(glbl_bigraph, redo)
      if fName[8:10] == 'nq':
        feat = FE.Bigraph_nq(glbl_bigraph, redo)
      if fName[8:10] == 'nr':
        feat = FE.Bigraph_nr(glbl_bigraph, redo)
      if fName[8:10] == 'ns':
        feat = FE.Bigraph_ns(glbl_bigraph, redo)
      if fName[8:10] == 'nt':
        feat = FE.Bigraph_nt(glbl_bigraph, redo)
      if fName[8:10] == 'nu':
        feat = FE.Bigraph_nu(glbl_bigraph, redo)
      if fName[8:10] == 'nv':
        feat = FE.Bigraph_nv(glbl_bigraph, redo)
      if fName[8:10] == 'nw':
        feat = FE.Bigraph_nw(glbl_bigraph, redo)
      if fName[8:10] == 'nx':
        feat = FE.Bigraph_nx(glbl_bigraph, redo)
      if fName[8:10] == 'ny':
        feat = FE.Bigraph_ny(glbl_bigraph, redo)
      if fName[8:10] == 'nz':
        feat = FE.Bigraph_nz(glbl_bigraph, redo)
      if fName[8:10] == 'oa':
        feat = FE.Bigraph_oa(glbl_bigraph, redo)
      if fName[8:10] == 'ob':
        feat = FE.Bigraph_ob(glbl_bigraph, redo)
      if fName[8:10] == 'oc':
        feat = FE.Bigraph_oc(glbl_bigraph, redo)
      if fName[8:10] == 'od':
        feat = FE.Bigraph_od(glbl_bigraph, redo)
      if fName[8:10] == 'oe':
        feat = FE.Bigraph_oe(glbl_bigraph, redo)
      if fName[8:10] == 'of':
        feat = FE.Bigraph_of(glbl_bigraph, redo)
      if fName[8:10] == 'og':
        feat = FE.Bigraph_og(glbl_bigraph, redo)
      if fName[8:10] == 'oh':
        feat = FE.Bigraph_oh(glbl_bigraph, redo)
      if fName[8:10] == 'oi':
        feat = FE.Bigraph_oi(glbl_bigraph, redo)
      if fName[8:10] == 'oj':
        feat = FE.Bigraph_oj(glbl_bigraph, redo)
      if fName[8:10] == 'ok':
        feat = FE.Bigraph_ok(glbl_bigraph, redo)
      if fName[8:10] == 'ol':
        feat = FE.Bigraph_ol(glbl_bigraph, redo)
      if fName[8:10] == 'om':
        feat = FE.Bigraph_om(glbl_bigraph, redo)
      if fName[8:10] == 'on':
        feat = FE.Bigraph_on(glbl_bigraph, redo)
      if fName[8:10] == 'oo':
        feat = FE.Bigraph_oo(glbl_bigraph, redo)
      if fName[8:10] == 'op':
        feat = FE.Bigraph_op(glbl_bigraph, redo)
      if fName[8:10] == 'oq':
        feat = FE.Bigraph_oq(glbl_bigraph, redo)
      if fName[8:10] == 'or':
        feat = FE.Bigraph_or(glbl_bigraph, redo)
      if fName[8:10] == 'os':
        feat = FE.Bigraph_os(glbl_bigraph, redo)
      if fName[8:10] == 'ot':
        feat = FE.Bigraph_ot(glbl_bigraph, redo)
      if fName[8:10] == 'ou':
        feat = FE.Bigraph_ou(glbl_bigraph, redo)
      if fName[8:10] == 'ov':
        feat = FE.Bigraph_ov(glbl_bigraph, redo)
      if fName[8:10] == 'ow':
        feat = FE.Bigraph_ow(glbl_bigraph, redo)
      if fName[8:10] == 'ox':
        feat = FE.Bigraph_ox(glbl_bigraph, redo)
      if fName[8:10] == 'oy':
        feat = FE.Bigraph_oy(glbl_bigraph, redo)
      if fName[8:10] == 'oz':
        feat = FE.Bigraph_oz(glbl_bigraph, redo)
      if fName[8:10] == 'pa':
        feat = FE.Bigraph_pa(glbl_bigraph, redo)
      if fName[8:10] == 'pb':
        feat = FE.Bigraph_pb(glbl_bigraph, redo)
      if fName[8:10] == 'pc':
        feat = FE.Bigraph_pc(glbl_bigraph, redo)
      if fName[8:10] == 'pd':
        feat = FE.Bigraph_pd(glbl_bigraph, redo)
      if fName[8:10] == 'pe':
        feat = FE.Bigraph_pe(glbl_bigraph, redo)
      if fName[8:10] == 'pf':
        feat = FE.Bigraph_pf(glbl_bigraph, redo)
      if fName[8:10] == 'pg':
        feat = FE.Bigraph_pg(glbl_bigraph, redo)
      if fName[8:10] == 'ph':
        feat = FE.Bigraph_ph(glbl_bigraph, redo)
      if fName[8:10] == 'pi':
        feat = FE.Bigraph_pi(glbl_bigraph, redo)
      if fName[8:10] == 'pj':
        feat = FE.Bigraph_pj(glbl_bigraph, redo)
      if fName[8:10] == 'pk':
        feat = FE.Bigraph_pk(glbl_bigraph, redo)
      if fName[8:10] == 'pl':
        feat = FE.Bigraph_pl(glbl_bigraph, redo)
      if fName[8:10] == 'pm':
        feat = FE.Bigraph_pm(glbl_bigraph, redo)
      if fName[8:10] == 'pn':
        feat = FE.Bigraph_pn(glbl_bigraph, redo)
      if fName[8:10] == 'po':
        feat = FE.Bigraph_po(glbl_bigraph, redo)
      if fName[8:10] == 'pp':
        feat = FE.Bigraph_pp(glbl_bigraph, redo)
      if fName[8:10] == 'pq':
        feat = FE.Bigraph_pq(glbl_bigraph, redo)
      if fName[8:10] == 'pr':
        feat = FE.Bigraph_pr(glbl_bigraph, redo)
      if fName[8:10] == 'ps':
        feat = FE.Bigraph_ps(glbl_bigraph, redo)
      if fName[8:10] == 'pt':
        feat = FE.Bigraph_pt(glbl_bigraph, redo)
      if fName[8:10] == 'pu':
        feat = FE.Bigraph_pu(glbl_bigraph, redo)
      if fName[8:10] == 'pv':
        feat = FE.Bigraph_pv(glbl_bigraph, redo)
      if fName[8:10] == 'pw':
        feat = FE.Bigraph_pw(glbl_bigraph, redo)
      if fName[8:10] == 'px':
        feat = FE.Bigraph_px(glbl_bigraph, redo)
      if fName[8:10] == 'py':
        feat = FE.Bigraph_py(glbl_bigraph, redo)
      if fName[8:10] == 'pz':
        feat = FE.Bigraph_pz(glbl_bigraph, redo)
      if fName[8:10] == 'qa':
        feat = FE.Bigraph_qa(glbl_bigraph, redo)
      if fName[8:10] == 'qb':
        feat = FE.Bigraph_qb(glbl_bigraph, redo)
      if fName[8:10] == 'qc':
        feat = FE.Bigraph_qc(glbl_bigraph, redo)
      if fName[8:10] == 'qd':
        feat = FE.Bigraph_qd(glbl_bigraph, redo)
      if fName[8:10] == 'qe':
        feat = FE.Bigraph_qe(glbl_bigraph, redo)
      if fName[8:10] == 'qf':
        feat = FE.Bigraph_qf(glbl_bigraph, redo)
      if fName[8:10] == 'qg':
        feat = FE.Bigraph_qg(glbl_bigraph, redo)
      if fName[8:10] == 'qh':
        feat = FE.Bigraph_qh(glbl_bigraph, redo)
      if fName[8:10] == 'qi':
        feat = FE.Bigraph_qi(glbl_bigraph, redo)
      if fName[8:10] == 'qj':
        feat = FE.Bigraph_qj(glbl_bigraph, redo)
      if fName[8:10] == 'qk':
        feat = FE.Bigraph_qk(glbl_bigraph, redo)
      if fName[8:10] == 'ql':
        feat = FE.Bigraph_ql(glbl_bigraph, redo)
      if fName[8:10] == 'qm':
        feat = FE.Bigraph_qm(glbl_bigraph, redo)
      if fName[8:10] == 'qn':
        feat = FE.Bigraph_qn(glbl_bigraph, redo)
      if fName[8:10] == 'qo':
        feat = FE.Bigraph_qo(glbl_bigraph, redo)
      if fName[8:10] == 'qp':
        feat = FE.Bigraph_qp(glbl_bigraph, redo)
      if fName[8:10] == 'qq':
        feat = FE.Bigraph_qq(glbl_bigraph, redo)
      if fName[8:10] == 'qr':
        feat = FE.Bigraph_qr(glbl_bigraph, redo)
      if fName[8:10] == 'qs':
        feat = FE.Bigraph_qs(glbl_bigraph, redo)
      if fName[8:10] == 'qt':
        feat = FE.Bigraph_qt(glbl_bigraph, redo)
      if fName[8:10] == 'qu':
        feat = FE.Bigraph_qu(glbl_bigraph, redo)
      if fName[8:10] == 'qv':
        feat = FE.Bigraph_qv(glbl_bigraph, redo)
      if fName[8:10] == 'qw':
        feat = FE.Bigraph_qw(glbl_bigraph, redo)
      if fName[8:10] == 'qx':
        feat = FE.Bigraph_qx(glbl_bigraph, redo)
      if fName[8:10] == 'qy':
        feat = FE.Bigraph_qy(glbl_bigraph, redo)
      if fName[8:10] == 'qz':
        feat = FE.Bigraph_qz(glbl_bigraph, redo)
      if fName[8:10] == 'ra':
        feat = FE.Bigraph_ra(glbl_bigraph, redo)
      if fName[8:10] == 'rb':
        feat = FE.Bigraph_rb(glbl_bigraph, redo)
      if fName[8:10] == 'rc':
        feat = FE.Bigraph_rc(glbl_bigraph, redo)
      if fName[8:10] == 'rd':
        feat = FE.Bigraph_rd(glbl_bigraph, redo)
      if fName[8:10] == 're':
        feat = FE.Bigraph_re(glbl_bigraph, redo)
      if fName[8:10] == 'rf':
        feat = FE.Bigraph_rf(glbl_bigraph, redo)
      if fName[8:10] == 'rg':
        feat = FE.Bigraph_rg(glbl_bigraph, redo)
      if fName[8:10] == 'rh':
        feat = FE.Bigraph_rh(glbl_bigraph, redo)
      if fName[8:10] == 'ri':
        feat = FE.Bigraph_ri(glbl_bigraph, redo)
      if fName[8:10] == 'rj':
        feat = FE.Bigraph_rj(glbl_bigraph, redo)
      if fName[8:10] == 'rk':
        feat = FE.Bigraph_rk(glbl_bigraph, redo)
      if fName[8:10] == 'rl':
        feat = FE.Bigraph_rl(glbl_bigraph, redo)
      if fName[8:10] == 'rm':
        feat = FE.Bigraph_rm(glbl_bigraph, redo)
      if fName[8:10] == 'rn':
        feat = FE.Bigraph_rn(glbl_bigraph, redo)
      if fName[8:10] == 'ro':
        feat = FE.Bigraph_ro(glbl_bigraph, redo)
      if fName[8:10] == 'rp':
        feat = FE.Bigraph_rp(glbl_bigraph, redo)
      if fName[8:10] == 'rq':
        feat = FE.Bigraph_rq(glbl_bigraph, redo)
      if fName[8:10] == 'rr':
        feat = FE.Bigraph_rr(glbl_bigraph, redo)
      if fName[8:10] == 'rs':
        feat = FE.Bigraph_rs(glbl_bigraph, redo)
      if fName[8:10] == 'rt':
        feat = FE.Bigraph_rt(glbl_bigraph, redo)
      if fName[8:10] == 'ru':
        feat = FE.Bigraph_ru(glbl_bigraph, redo)
      if fName[8:10] == 'rv':
        feat = FE.Bigraph_rv(glbl_bigraph, redo)
      if fName[8:10] == 'rw':
        feat = FE.Bigraph_rw(glbl_bigraph, redo)
      if fName[8:10] == 'rx':
        feat = FE.Bigraph_rx(glbl_bigraph, redo)
      if fName[8:10] == 'ry':
        feat = FE.Bigraph_ry(glbl_bigraph, redo)
      if fName[8:10] == 'rz':
        feat = FE.Bigraph_rz(glbl_bigraph, redo)
      if fName[8:10] == 'sa':
        feat = FE.Bigraph_sa(glbl_bigraph, redo)
      if fName[8:10] == 'sb':
        feat = FE.Bigraph_sb(glbl_bigraph, redo)
      if fName[8:10] == 'sc':
        feat = FE.Bigraph_sc(glbl_bigraph, redo)
      if fName[8:10] == 'sd':
        feat = FE.Bigraph_sd(glbl_bigraph, redo)
      if fName[8:10] == 'se':
        feat = FE.Bigraph_se(glbl_bigraph, redo)
      if fName[8:10] == 'sf':
        feat = FE.Bigraph_sf(glbl_bigraph, redo)
      if fName[8:10] == 'sg':
        feat = FE.Bigraph_sg(glbl_bigraph, redo)
      if fName[8:10] == 'sh':
        feat = FE.Bigraph_sh(glbl_bigraph, redo)
      if fName[8:10] == 'si':
        feat = FE.Bigraph_si(glbl_bigraph, redo)
      if fName[8:10] == 'sj':
        feat = FE.Bigraph_sj(glbl_bigraph, redo)
      if fName[8:10] == 'sk':
        feat = FE.Bigraph_sk(glbl_bigraph, redo)
      if fName[8:10] == 'sl':
        feat = FE.Bigraph_sl(glbl_bigraph, redo)
      if fName[8:10] == 'sm':
        feat = FE.Bigraph_sm(glbl_bigraph, redo)
      if fName[8:10] == 'sn':
        feat = FE.Bigraph_sn(glbl_bigraph, redo)
      if fName[8:10] == 'so':
        feat = FE.Bigraph_so(glbl_bigraph, redo)
      if fName[8:10] == 'sp':
        feat = FE.Bigraph_sp(glbl_bigraph, redo)
      if fName[8:10] == 'sq':
        feat = FE.Bigraph_sq(glbl_bigraph, redo)
      if fName[8:10] == 'sr':
        feat = FE.Bigraph_sr(glbl_bigraph, redo)
      if fName[8:10] == 'ss':
        feat = FE.Bigraph_ss(glbl_bigraph, redo)
      if fName[8:10] == 'st':
        feat = FE.Bigraph_st(glbl_bigraph, redo)
      if fName[8:10] == 'su':
        feat = FE.Bigraph_su(glbl_bigraph, redo)
      if fName[8:10] == 'sv':
        feat = FE.Bigraph_sv(glbl_bigraph, redo)
      if fName[8:10] == 'sw':
        feat = FE.Bigraph_sw(glbl_bigraph, redo)
      if fName[8:10] == 'sx':
        feat = FE.Bigraph_sx(glbl_bigraph, redo)
      if fName[8:10] == 'sy':
        feat = FE.Bigraph_sy(glbl_bigraph, redo)
      if fName[8:10] == 'sz':
        feat = FE.Bigraph_sz(glbl_bigraph, redo)
      if fName[8:10] == 'ta':
        feat = FE.Bigraph_ta(glbl_bigraph, redo)
      if fName[8:10] == 'tb':
        feat = FE.Bigraph_tb(glbl_bigraph, redo)
      if fName[8:10] == 'tc':
        feat = FE.Bigraph_tc(glbl_bigraph, redo)
      if fName[8:10] == 'td':
        feat = FE.Bigraph_td(glbl_bigraph, redo)
      if fName[8:10] == 'te':
        feat = FE.Bigraph_te(glbl_bigraph, redo)
      if fName[8:10] == 'tf':
        feat = FE.Bigraph_tf(glbl_bigraph, redo)
      if fName[8:10] == 'tg':
        feat = FE.Bigraph_tg(glbl_bigraph, redo)
      if fName[8:10] == 'th':
        feat = FE.Bigraph_th(glbl_bigraph, redo)
      if fName[8:10] == 'ti':
        feat = FE.Bigraph_ti(glbl_bigraph, redo)
      if fName[8:10] == 'tj':
        feat = FE.Bigraph_tj(glbl_bigraph, redo)
      if fName[8:10] == 'tk':
        feat = FE.Bigraph_tk(glbl_bigraph, redo)
      if fName[8:10] == 'tl':
        feat = FE.Bigraph_tl(glbl_bigraph, redo)
      if fName[8:10] == 'tm':
        feat = FE.Bigraph_tm(glbl_bigraph, redo)
      if fName[8:10] == 'tn':
        feat = FE.Bigraph_tn(glbl_bigraph, redo)
      if fName[8:10] == 'to':
        feat = FE.Bigraph_to(glbl_bigraph, redo)
      if fName[8:10] == 'tp':
        feat = FE.Bigraph_tp(glbl_bigraph, redo)
      if fName[8:10] == 'tq':
        feat = FE.Bigraph_tq(glbl_bigraph, redo)
      if fName[8:10] == 'tr':
        feat = FE.Bigraph_tr(glbl_bigraph, redo)
      if fName[8:10] == 'ts':
        feat = FE.Bigraph_ts(glbl_bigraph, redo)
      if fName[8:10] == 'tt':
        feat = FE.Bigraph_tt(glbl_bigraph, redo)
      if fName[8:10] == 'tu':
        feat = FE.Bigraph_tu(glbl_bigraph, redo)
      if fName[8:10] == 'tv':
        feat = FE.Bigraph_tv(glbl_bigraph, redo)
      if fName[8:10] == 'tw':
        feat = FE.Bigraph_tw(glbl_bigraph, redo)
      if fName[8:10] == 'tx':
        feat = FE.Bigraph_tx(glbl_bigraph, redo)
      if fName[8:10] == 'ty':
        feat = FE.Bigraph_ty(glbl_bigraph, redo)
      if fName[8:10] == 'tz':
        feat = FE.Bigraph_tz(glbl_bigraph, redo)
      if fName[8:10] == 'ua':
        feat = FE.Bigraph_ua(glbl_bigraph, redo)
      if fName[8:10] == 'ub':
        feat = FE.Bigraph_ub(glbl_bigraph, redo)
      if fName[8:10] == 'uc':
        feat = FE.Bigraph_uc(glbl_bigraph, redo)
      if fName[8:10] == 'ud':
        feat = FE.Bigraph_ud(glbl_bigraph, redo)
      if fName[8:10] == 'ue':
        feat = FE.Bigraph_ue(glbl_bigraph, redo)
      if fName[8:10] == 'uf':
        feat = FE.Bigraph_uf(glbl_bigraph, redo)
      if fName[8:10] == 'ug':
        feat = FE.Bigraph_ug(glbl_bigraph, redo)
      if fName[8:10] == 'uh':
        feat = FE.Bigraph_uh(glbl_bigraph, redo)
      if fName[8:10] == 'ui':
        feat = FE.Bigraph_ui(glbl_bigraph, redo)
      if fName[8:10] == 'uj':
        feat = FE.Bigraph_uj(glbl_bigraph, redo)
      if fName[8:10] == 'uk':
        feat = FE.Bigraph_uk(glbl_bigraph, redo)
      if fName[8:10] == 'ul':
        feat = FE.Bigraph_ul(glbl_bigraph, redo)
      if fName[8:10] == 'um':
        feat = FE.Bigraph_um(glbl_bigraph, redo)
      if fName[8:10] == 'un':
        feat = FE.Bigraph_un(glbl_bigraph, redo)
      if fName[8:10] == 'uo':
        feat = FE.Bigraph_uo(glbl_bigraph, redo)
      if fName[8:10] == 'up':
        feat = FE.Bigraph_up(glbl_bigraph, redo)
      if fName[8:10] == 'uq':
        feat = FE.Bigraph_uq(glbl_bigraph, redo)
      if fName[8:10] == 'ur':
        feat = FE.Bigraph_ur(glbl_bigraph, redo)
      if fName[8:10] == 'us':
        feat = FE.Bigraph_us(glbl_bigraph, redo)
      if fName[8:10] == 'ut':
        feat = FE.Bigraph_ut(glbl_bigraph, redo)
      if fName[8:10] == 'uu':
        feat = FE.Bigraph_uu(glbl_bigraph, redo)
      if fName[8:10] == 'uv':
        feat = FE.Bigraph_uv(glbl_bigraph, redo)
      if fName[8:10] == 'uw':
        feat = FE.Bigraph_uw(glbl_bigraph, redo)
      if fName[8:10] == 'ux':
        feat = FE.Bigraph_ux(glbl_bigraph, redo)
      if fName[8:10] == 'uy':
        feat = FE.Bigraph_uy(glbl_bigraph, redo)
      if fName[8:10] == 'uz':
        feat = FE.Bigraph_uz(glbl_bigraph, redo)
      if fName[8:10] == 'va':
        feat = FE.Bigraph_va(glbl_bigraph, redo)
      if fName[8:10] == 'vb':
        feat = FE.Bigraph_vb(glbl_bigraph, redo)
      if fName[8:10] == 'vc':
        feat = FE.Bigraph_vc(glbl_bigraph, redo)
      if fName[8:10] == 'vd':
        feat = FE.Bigraph_vd(glbl_bigraph, redo)
      if fName[8:10] == 've':
        feat = FE.Bigraph_ve(glbl_bigraph, redo)
      if fName[8:10] == 'vf':
        feat = FE.Bigraph_vf(glbl_bigraph, redo)
      if fName[8:10] == 'vg':
        feat = FE.Bigraph_vg(glbl_bigraph, redo)
      if fName[8:10] == 'vh':
        feat = FE.Bigraph_vh(glbl_bigraph, redo)
      if fName[8:10] == 'vi':
        feat = FE.Bigraph_vi(glbl_bigraph, redo)
      if fName[8:10] == 'vj':
        feat = FE.Bigraph_vj(glbl_bigraph, redo)
      if fName[8:10] == 'vk':
        feat = FE.Bigraph_vk(glbl_bigraph, redo)
      if fName[8:10] == 'vl':
        feat = FE.Bigraph_vl(glbl_bigraph, redo)
      if fName[8:10] == 'vm':
        feat = FE.Bigraph_vm(glbl_bigraph, redo)
      if fName[8:10] == 'vn':
        feat = FE.Bigraph_vn(glbl_bigraph, redo)
      if fName[8:10] == 'vo':
        feat = FE.Bigraph_vo(glbl_bigraph, redo)
      if fName[8:10] == 'vp':
        feat = FE.Bigraph_vp(glbl_bigraph, redo)
      if fName[8:10] == 'vq':
        feat = FE.Bigraph_vq(glbl_bigraph, redo)
      if fName[8:10] == 'vr':
        feat = FE.Bigraph_vr(glbl_bigraph, redo)
      if fName[8:10] == 'vs':
        feat = FE.Bigraph_vs(glbl_bigraph, redo)
      if fName[8:10] == 'vt':
        feat = FE.Bigraph_vt(glbl_bigraph, redo)
      if fName[8:10] == 'vu':
        feat = FE.Bigraph_vu(glbl_bigraph, redo)
      if fName[8:10] == 'vv':
        feat = FE.Bigraph_vv(glbl_bigraph, redo)
      if fName[8:10] == 'vw':
        feat = FE.Bigraph_vw(glbl_bigraph, redo)
      if fName[8:10] == 'vx':
        feat = FE.Bigraph_vx(glbl_bigraph, redo)
      if fName[8:10] == 'vy':
        feat = FE.Bigraph_vy(glbl_bigraph, redo)
      if fName[8:10] == 'vz':
        feat = FE.Bigraph_vz(glbl_bigraph, redo)
      if fName[8:10] == 'wa':
        feat = FE.Bigraph_wa(glbl_bigraph, redo)
      if fName[8:10] == 'wb':
        feat = FE.Bigraph_wb(glbl_bigraph, redo)
      if fName[8:10] == 'wc':
        feat = FE.Bigraph_wc(glbl_bigraph, redo)
      if fName[8:10] == 'wd':
        feat = FE.Bigraph_wd(glbl_bigraph, redo)
      if fName[8:10] == 'we':
        feat = FE.Bigraph_we(glbl_bigraph, redo)
      if fName[8:10] == 'wf':
        feat = FE.Bigraph_wf(glbl_bigraph, redo)
      if fName[8:10] == 'wg':
        feat = FE.Bigraph_wg(glbl_bigraph, redo)
      if fName[8:10] == 'wh':
        feat = FE.Bigraph_wh(glbl_bigraph, redo)
      if fName[8:10] == 'wi':
        feat = FE.Bigraph_wi(glbl_bigraph, redo)
      if fName[8:10] == 'wj':
        feat = FE.Bigraph_wj(glbl_bigraph, redo)
      if fName[8:10] == 'wk':
        feat = FE.Bigraph_wk(glbl_bigraph, redo)
      if fName[8:10] == 'wl':
        feat = FE.Bigraph_wl(glbl_bigraph, redo)
      if fName[8:10] == 'wm':
        feat = FE.Bigraph_wm(glbl_bigraph, redo)
      if fName[8:10] == 'wn':
        feat = FE.Bigraph_wn(glbl_bigraph, redo)
      if fName[8:10] == 'wo':
        feat = FE.Bigraph_wo(glbl_bigraph, redo)
      if fName[8:10] == 'wp':
        feat = FE.Bigraph_wp(glbl_bigraph, redo)
      if fName[8:10] == 'wq':
        feat = FE.Bigraph_wq(glbl_bigraph, redo)
      if fName[8:10] == 'wr':
        feat = FE.Bigraph_wr(glbl_bigraph, redo)
      if fName[8:10] == 'ws':
        feat = FE.Bigraph_ws(glbl_bigraph, redo)
      if fName[8:10] == 'wt':
        feat = FE.Bigraph_wt(glbl_bigraph, redo)
      if fName[8:10] == 'wu':
        feat = FE.Bigraph_wu(glbl_bigraph, redo)
      if fName[8:10] == 'wv':
        feat = FE.Bigraph_wv(glbl_bigraph, redo)
      if fName[8:10] == 'ww':
        feat = FE.Bigraph_ww(glbl_bigraph, redo)
      if fName[8:10] == 'wx':
        feat = FE.Bigraph_wx(glbl_bigraph, redo)
      if fName[8:10] == 'wy':
        feat = FE.Bigraph_wy(glbl_bigraph, redo)
      if fName[8:10] == 'wz':
        feat = FE.Bigraph_wz(glbl_bigraph, redo)
      if fName[8:10] == 'xa':
        feat = FE.Bigraph_xa(glbl_bigraph, redo)
      if fName[8:10] == 'xb':
        feat = FE.Bigraph_xb(glbl_bigraph, redo)
      if fName[8:10] == 'xc':
        feat = FE.Bigraph_xc(glbl_bigraph, redo)
      if fName[8:10] == 'xd':
        feat = FE.Bigraph_xd(glbl_bigraph, redo)
      if fName[8:10] == 'xe':
        feat = FE.Bigraph_xe(glbl_bigraph, redo)
      if fName[8:10] == 'xf':
        feat = FE.Bigraph_xf(glbl_bigraph, redo)
      if fName[8:10] == 'xg':
        feat = FE.Bigraph_xg(glbl_bigraph, redo)
      if fName[8:10] == 'xh':
        feat = FE.Bigraph_xh(glbl_bigraph, redo)
      if fName[8:10] == 'xi':
        feat = FE.Bigraph_xi(glbl_bigraph, redo)
      if fName[8:10] == 'xj':
        feat = FE.Bigraph_xj(glbl_bigraph, redo)
      if fName[8:10] == 'xk':
        feat = FE.Bigraph_xk(glbl_bigraph, redo)
      if fName[8:10] == 'xl':
        feat = FE.Bigraph_xl(glbl_bigraph, redo)
      if fName[8:10] == 'xm':
        feat = FE.Bigraph_xm(glbl_bigraph, redo)
      if fName[8:10] == 'xn':
        feat = FE.Bigraph_xn(glbl_bigraph, redo)
      if fName[8:10] == 'xo':
        feat = FE.Bigraph_xo(glbl_bigraph, redo)
      if fName[8:10] == 'xp':
        feat = FE.Bigraph_xp(glbl_bigraph, redo)
      if fName[8:10] == 'xq':
        feat = FE.Bigraph_xq(glbl_bigraph, redo)
      if fName[8:10] == 'xr':
        feat = FE.Bigraph_xr(glbl_bigraph, redo)
      if fName[8:10] == 'xs':
        feat = FE.Bigraph_xs(glbl_bigraph, redo)
      if fName[8:10] == 'xt':
        feat = FE.Bigraph_xt(glbl_bigraph, redo)
      if fName[8:10] == 'xu':
        feat = FE.Bigraph_xu(glbl_bigraph, redo)
      if fName[8:10] == 'xv':
        feat = FE.Bigraph_xv(glbl_bigraph, redo)
      if fName[8:10] == 'xw':
        feat = FE.Bigraph_xw(glbl_bigraph, redo)
      if fName[8:10] == 'xx':
        feat = FE.Bigraph_xx(glbl_bigraph, redo)
      if fName[8:10] == 'xy':
        feat = FE.Bigraph_xy(glbl_bigraph, redo)
      if fName[8:10] == 'xz':
        feat = FE.Bigraph_xz(glbl_bigraph, redo)
      if fName[8:10] == 'ya':
        feat = FE.Bigraph_ya(glbl_bigraph, redo)
      if fName[8:10] == 'yb':
        feat = FE.Bigraph_yb(glbl_bigraph, redo)
      if fName[8:10] == 'yc':
        feat = FE.Bigraph_yc(glbl_bigraph, redo)
      if fName[8:10] == 'yd':
        feat = FE.Bigraph_yd(glbl_bigraph, redo)
      if fName[8:10] == 'ye':
        feat = FE.Bigraph_ye(glbl_bigraph, redo)
      if fName[8:10] == 'yf':
        feat = FE.Bigraph_yf(glbl_bigraph, redo)
      if fName[8:10] == 'yg':
        feat = FE.Bigraph_yg(glbl_bigraph, redo)
      if fName[8:10] == 'yh':
        feat = FE.Bigraph_yh(glbl_bigraph, redo)
      if fName[8:10] == 'yi':
        feat = FE.Bigraph_yi(glbl_bigraph, redo)
      if fName[8:10] == 'yj':
        feat = FE.Bigraph_yj(glbl_bigraph, redo)
      if fName[8:10] == 'yk':
        feat = FE.Bigraph_yk(glbl_bigraph, redo)
      if fName[8:10] == 'yl':
        feat = FE.Bigraph_yl(glbl_bigraph, redo)
      if fName[8:10] == 'ym':
        feat = FE.Bigraph_ym(glbl_bigraph, redo)
      if fName[8:10] == 'yn':
        feat = FE.Bigraph_yn(glbl_bigraph, redo)
      if fName[8:10] == 'yo':
        feat = FE.Bigraph_yo(glbl_bigraph, redo)
      if fName[8:10] == 'yp':
        feat = FE.Bigraph_yp(glbl_bigraph, redo)
      if fName[8:10] == 'yq':
        feat = FE.Bigraph_yq(glbl_bigraph, redo)
      if fName[8:10] == 'yr':
        feat = FE.Bigraph_yr(glbl_bigraph, redo)
      if fName[8:10] == 'ys':
        feat = FE.Bigraph_ys(glbl_bigraph, redo)
      if fName[8:10] == 'yt':
        feat = FE.Bigraph_yt(glbl_bigraph, redo)
      if fName[8:10] == 'yu':
        feat = FE.Bigraph_yu(glbl_bigraph, redo)
      if fName[8:10] == 'yv':
        feat = FE.Bigraph_yv(glbl_bigraph, redo)
      if fName[8:10] == 'yw':
        feat = FE.Bigraph_yw(glbl_bigraph, redo)
      if fName[8:10] == 'yx':
        feat = FE.Bigraph_yx(glbl_bigraph, redo)
      if fName[8:10] == 'yy':
        feat = FE.Bigraph_yy(glbl_bigraph, redo)
      if fName[8:10] == 'yz':
        feat = FE.Bigraph_yz(glbl_bigraph, redo)
      if fName[8:10] == 'za':
        feat = FE.Bigraph_za(glbl_bigraph, redo)
      if fName[8:10] == 'zb':
        feat = FE.Bigraph_zb(glbl_bigraph, redo)
      if fName[8:10] == 'zc':
        feat = FE.Bigraph_zc(glbl_bigraph, redo)
      if fName[8:10] == 'zd':
        feat = FE.Bigraph_zd(glbl_bigraph, redo)
      if fName[8:10] == 'ze':
        feat = FE.Bigraph_ze(glbl_bigraph, redo)
      if fName[8:10] == 'zf':
        feat = FE.Bigraph_zf(glbl_bigraph, redo)
      if fName[8:10] == 'zg':
        feat = FE.Bigraph_zg(glbl_bigraph, redo)
      if fName[8:10] == 'zh':
        feat = FE.Bigraph_zh(glbl_bigraph, redo)
      if fName[8:10] == 'zi':
        feat = FE.Bigraph_zi(glbl_bigraph, redo)
      if fName[8:10] == 'zj':
        feat = FE.Bigraph_zj(glbl_bigraph, redo)
      if fName[8:10] == 'zk':
        feat = FE.Bigraph_zk(glbl_bigraph, redo)
      if fName[8:10] == 'zl':
        feat = FE.Bigraph_zl(glbl_bigraph, redo)
      if fName[8:10] == 'zm':
        feat = FE.Bigraph_zm(glbl_bigraph, redo)
      if fName[8:10] == 'zn':
        feat = FE.Bigraph_zn(glbl_bigraph, redo)
      if fName[8:10] == 'zo':
        feat = FE.Bigraph_zo(glbl_bigraph, redo)
      if fName[8:10] == 'zp':
        feat = FE.Bigraph_zp(glbl_bigraph, redo)
      if fName[8:10] == 'zq':
        feat = FE.Bigraph_zq(glbl_bigraph, redo)
      if fName[8:10] == 'zr':
        feat = FE.Bigraph_zr(glbl_bigraph, redo)
      if fName[8:10] == 'zs':
        feat = FE.Bigraph_zs(glbl_bigraph, redo)
      if fName[8:10] == 'zt':
        feat = FE.Bigraph_zt(glbl_bigraph, redo)
      if fName[8:10] == 'zu':
        feat = FE.Bigraph_zu(glbl_bigraph, redo)
      if fName[8:10] == 'zv':
        feat = FE.Bigraph_zv(glbl_bigraph, redo)
      if fName[8:10] == 'zw':
        feat = FE.Bigraph_zw(glbl_bigraph, redo)
      if fName[8:10] == 'zx':
        feat = FE.Bigraph_zx(glbl_bigraph, redo)
      if fName[8:10] == 'zy':
        feat = FE.Bigraph_zy(glbl_bigraph, redo)
      if fName[8:10] == 'zz':
        feat = FE.Bigraph_zz(glbl_bigraph, redo)

    if (feat != None):
      try:
        feat.discretization = discretizations[feat.nickname]
      except:
        None == None
      features.append(feat)
  return features

def LoadData(users, features):
  classAssignments = []
  featureVectors = []
  for user in users:
    classification = users.index(user)
    print(" Extracting "+user)
    dir = "../Data/"+user
    posts = os.listdir(dir)
    i = 0
    for postfile in posts:
      #if i > 50: break
      vec = []
      f = codecs.open(dir+"/"+postfile,'r',"utf-8")
      posttext = f.read()
      f.close()
      post = Post.Post(posttext)
      if len(post.words) == 0:
      #if len(post.words) < 21:
        continue
      i += 1
      for feature in features:
        vec.append(feature.Extract(post))
      featureVectors.append(np.array(vec))
      classAssignments.append(classification)
  featureVectors = np.array(featureVectors)
  return classAssignments, featureVectors

def ScaleData(featureVectors):
  for i in range(0,featureVectors.shape[1]):
    featureVectors[:,i] -= np.average(featureVectors[:,i])
    featureVectors[:,i] /= np.std(featureVectors[:,i])
